server:
  port: 7501
spring:
  application:
    name: gateway
 ## api-aaa指模块名
 ## 这里的配置表示，访问/mv/** 直接重定向到https://mvnrepository.com/**
#zuul:
#  routes:
#    api-aaa:
#      path: /mv/**
#      url: https://mvnrepository.com/
      ## 配置子模块eureka-consumer的路由规则
#    api-cons:
#      path: /cons/**
#      serviceId: eureka-consumer
   ## 向注册中心注册
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:7101/eureka/,http://peer2:7102/eureka/


